### ISSUE TITLE
AToken Test Harness Setup

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/flexible-voting#6]
We want to implement Flexible Voting for ATokens inside the Aave system. To do so, we'll need a test harness that:

* Forks mainnet to interact with the Aave protocol
* Extends/implements an AToken for a mock ERC20Votes GOV token
* Adds the new GOV AToken market to Aave
* Can supply, borrow, liquidate, etc... for said market

**Comment by davidlaprade** [comment]
So that I keep all of this straight in my head, this is the usecase we're targeting:

* there is an ERC20, call it GOV
* GOV is the governance token issued by Protocol, which inherits from [GovernorCountingFractional](https://github.com/ScopeLift/flexible-voting/blob/master/src/GovernorCountingFractional.sol)
* I deposit some GOV into Aave and receive aGOV in return
* aGOV implements [FractionalPool](https://github.com/ScopeLift/flexible-voting/blob/master/src/FractionalPool.sol)-like functionality
* as proposals are made to Protocol, I can express my voting preference on them directly to aGOV
* aGOV will then cast fractionally weighted votes to Protocol according to the expressed voting preferences of its holders
